version: '3.8'

services:
    angular-project:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - NODE_ENV=production 
        ports:
            - 5000:80